scoreList:
- 'Клан {clan}'
- 'Имя: %player_name%'
- 'Мир: %player_world%'
- 'Баланс: %vault_eco_balance%'
- 'Префикс: %vault_prefix%'
- 'Ранг: %vault_rank%'
- 'Регион: {region}'
- 'Убито игроков: %statistic_player_kills%'
- 'Убито мобов: %statistic_mob_kills%'
- 'Смертей: %statistic_deaths%'
nameList:
- '               l'
- '              l '
- '             l  '
- '            l   '
- '           l    '
- '          l     '
- '         l      '
- '        l       '
- '       l        '
- '      l         '
- '     l          '
- '    l           '
- '   l            '
- '  l             '
- ' l              '
- 'l               '
- 'l              o'
- 'l             o '
- 'l            o  '
- 'l           o   '
- 'l          o    '
- 'l         o     '
- 'l        o      '
- 'l       o       '
- 'l      o        '
- 'l     o         '
- 'l    o          '
- 'l   o           '
- 'l  o            '
- 'l o             '
- 'lo              '
- 'lo             c'
- 'lo            c '
- 'lo           c  '
- 'lo          c   '
- 'lo         c    '
- 'lo        c     '
- 'lo       c      '
- 'lo      c       '
- 'lo     c        '
- 'lo    c         '
- 'lo   c          '
- 'lo  c           '
- 'lo c            '
- 'loc             '
- 'loc            a'
- 'loc           a '
- 'loc          a  '
- 'loc         a   '
- 'loc        a    '
- 'loc       a     '
- 'loc      a      '
- 'loc     a       '
- 'loc    a        '
- 'loc   a         '
- 'loc  a          '
- 'loc a           '
- 'loca            '
- 'loca           l'
- 'loca          l '
- 'loca         l  '
- 'loca        l   '
- 'loca       l    '
- 'loca      l     '
- 'loca     l      '
- 'loca    l       '
- 'loca   l        '
- 'loca  l         '
- 'loca l          '
- 'local           '
- 'local          h'
- 'local         h '
- 'local        h  '
- 'local       h   '
- 'local      h    '
- 'local     h     '
- 'local    h      '
- 'local   h       '
- 'local  h        '
- 'local h         '
- 'localh          '
- 'localh         o'
- 'localh        o '
- 'localh       o  '
- 'localh      o   '
- 'localh     o    '
- 'localh    o     '
- 'localh   o      '
- 'localh  o       '
- 'localh o        '
- 'localho         '
- 'localho        s'
- 'localho       s '
- 'localho      s  '
- 'localho     s   '
- 'localho    s    '
- 'localho   s     '
- 'localho  s      '
- 'localho s       '
- 'localhos        '
- 'localhos       t'
- 'localhos      t '
- 'localhos     t  '
- 'localhos    t   '
- 'localhos   t    '
- 'localhos  t     '
- 'localhos t      '
- 'localhost       '
- 'localhost       '
- 'localhost       '
- 'localhost       '
- 'localhost       '
- 'localhost       '
- 'localhost       '
- 'localhost       '
- 'localhost       '
- 'localhost       '
- 'localhost       '
- 'localhost       '
- 'localhost       '
- 'localhost       '
- 'localhost       '
- 'localhost       '
- 'localhost       '
- 'localhost       '
- 'localhost       '
- 'localhost       '
- 'localhost       '
- 'localhost       '
- 'localhost       '
- 'localhost       '
- 'localhost       '
- 'localhost       '
- 'localhost       '
- 'localhost       '